version: '3'
services:
    api:
        image: hello
        build: .
        networks:
            - backend
        ports:
            - "3000:3000"
        volumes:
            - ./:/usr/src/app

    web-cli:
        image: hello
        networks:
            - backend
        command: sh

networks:
    backend:
        driver: bridge
